### ISSUE TITLE
Add United Manufacturing Hub as a commercial, open-source implementation

### ISSUE THREAD

**Issue by JeremyTheocharis** [mkashwin/unifiednamespace#2]
Hi @mkashwin,

would it be okay for you to include the [United Manufacturing Hub as a commercial, open-source implementation of a Unified Namespace](https://learn.umh.app) in your README? 

I stumbled again across your project and there are a lot of similarities.

Regards,
Jeremy

**Comment by JeremyTheocharis** [comment]
I created a PR with a proposal: #3 

Thank you!

**Comment by mkashwin** [comment]
PR merged
